library(dplyr)
if(!file.exists("./data")){dir.create("./data")}
## At first I downloaded all files on PC
## Step 1. "Merges the training and the test sets to create one data set".
## 1. Read files in variables (in memory of PC)
filesurl="D:/MOOC/Coursera_3_Getting and Cleaning Data/Course Project/getdata-projectfiles-UCI HAR Dataset/UCI HAR Dataset/"
## read files from the main folder
T <- filesurl
T1 <- paste(T,"activity_labels.txt",sep="")
Labels <- read.table(T1)
T1 <- paste(T,"features.txt",sep="")
Features <- read.table(T1)
## read files from the folder "test"
T <- paste(filesurl,"test/",sep="")
T1 <- paste(T,"X_test.txt",sep="")
T_X <- read.table(T1)
T1 <- paste(T,"Y_test.txt",sep="")
T_Y <- read.table(T1)
T1 <- paste(T,"subject_test.txt",sep="")
T_S <- read.table(T1)
T <- paste(T,"Inertial Signals/",sep="")
T1 <- paste(T,"body_acc_x_test.txt",sep="")
T_BAX <- read.table(T1)
T1 <- paste(T,"body_acc_y_test.txt",sep="")
T_BAY <- read.table(T1)
T1 <- paste(T,"body_acc_z_test.txt",sep="")
T_BAZ <- read.table(T1)
T1 <- paste(T,"body_gyro_x_test.txt",sep="")
T_BGX <- read.table(T1)
T1 <- paste(T,"body_gyro_y_test.txt",sep="")
T_BGY <- read.table(T1)
T1 <- paste(T,"body_gyro_z_test.txt",sep="")
T_BGZ <- read.table(T1)
T1 <- paste(T,"total_acc_x_test.txt",sep="")
T_TAX <- read.table(T1)
T1 <- paste(T,"total_acc_y_test.txt",sep="")
T_TAY <- read.table(T1)
T1 <- paste(T,"total_acc_z_test.txt",sep="")
T_TAZ <- read.table(T1)
## read files from the folder "train"
T <- paste(filesurl,"train/",sep="")
T1 <- paste(T,"X_train.txt",sep="")
TR_X <- read.table(T1)
T1 <- paste(T,"Y_train.txt",sep="")
TR_Y <- read.table(T1)
T1 <- paste(T,"subject_train.txt",sep="")
TR_S <- read.table(T1)
T <- paste(T,"Inertial Signals/",sep="")
T1 <- paste(T,"body_acc_x_train.txt",sep="")
TR_BAX <- read.table(T1)
T1 <- paste(T,"body_acc_y_train.txt",sep="")
TR_BAY <- read.table(T1)
T1 <- paste(T,"body_acc_z_train.txt",sep="")
TR_BAZ <- read.table(T1)
T1 <- paste(T,"body_gyro_x_train.txt",sep="")
TR_BGX <- read.table(T1)
T1 <- paste(T,"body_gyro_y_train.txt",sep="")
TR_BGY <- read.table(T1)
T1 <- paste(T,"body_gyro_z_train.txt",sep="")
TR_BGZ <- read.table(T1)
T1 <- paste(T,"total_acc_x_train.txt",sep="")
TR_TAX <- read.table(T1)
T1 <- paste(T,"total_acc_y_train.txt",sep="")
TR_TAY <- read.table(T1)
T1 <- paste(T,"total_acc_z_train.txt",sep="")
TR_TAZ <- read.table(T1)
## 2. Merge of the test and train data for each parameters
SX <- rbind(T_X,TR_X)
SY <- rbind(T_Y,TR_Y)
SS <- rbind(T_S,TR_S)
BAX <- rbind(T_BAX,TR_BAX)
BAY <- rbind(T_BAY,TR_BAY)
BAZ <- rbind(T_BAZ,TR_BAZ)
BGX <- rbind(T_BGX,TR_BGX)
BGY <- rbind(T_BGY,TR_BGY)
BGZ <- rbind(T_BGZ,TR_BGZ)
TAX <- rbind(T_TAX,TR_TAX)
TAY <- rbind(T_TAY,TR_TAY)
TAZ <- rbind(T_TAZ,TR_TAZ)
##
## Step 3. "Uses descriptive activity names to name the activities in the data set"
## and Step 4. Appropriately labels the data set with descriptive variable names. 
names(SX)=sapply(Features$V2, as.character)
##
## Step 2. "Extracts only the measurements on the mean and standard deviation for each measurement".
P_mean <- filter(Features,grepl("mean\\(",Features$V2))
P_std <- filter(Features,grepl("std",Features$V2))
PP <- c(P_mean$V1,P_std$V1)
SX2 <- SX[,PP]
write.table(SX2, file = "D:/MOOC/Coursera_3_Getting and Cleaning Data/Course Project/rezults.txt", sep = ",",row.name=FALSE)